// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TPDojo.Data;

#nullable disable

namespace TPDojo.Migrations
{
    [DbContext(typeof(TPDojoContext))]
    [Migration("20220225152054_avecDonnees")]
    partial class avecDonnees
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BO.Arme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Degats")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Armes");
                });

            modelBuilder.Entity("BO.Samourai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("ArmeId")
                        .HasColumnType("int");

                    b.Property<int>("Force")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArmeId");

                    b.ToTable("Samourais");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Force = 1254,
                            Nom = "Abe Masakatsu"
                        },
                        new
                        {
                            Id = 2,
                            Force = 748,
                            Nom = "Adachi Yasumori"
                        },
                        new
                        {
                            Id = 3,
                            Force = 732,
                            Nom = "Adachi Kagemori"
                        },
                        new
                        {
                            Id = 4,
                            Force = 1579,
                            Nom = "Adams William"
                        },
                        new
                        {
                            Id = 5,
                            Force = 1885,
                            Nom = "Aiou Mototsuna"
                        },
                        new
                        {
                            Id = 6,
                            Force = 1467,
                            Nom = "Akai Terukage"
                        },
                        new
                        {
                            Id = 7,
                            Force = 24,
                            Nom = "Akao Kiyotsuna"
                        },
                        new
                        {
                            Id = 8,
                            Force = 644,
                            Nom = "Akechi Mitsuhide"
                        },
                        new
                        {
                            Id = 9,
                            Force = 1176,
                            Nom = "Akiyama Nobutomo"
                        },
                        new
                        {
                            Id = 10,
                            Force = 504,
                            Nom = "Amago Haruhisa"
                        },
                        new
                        {
                            Id = 11,
                            Force = 416,
                            Nom = "Amago Yoshihisa"
                        },
                        new
                        {
                            Id = 12,
                            Force = 1677,
                            Nom = "Andō Morinari"
                        },
                        new
                        {
                            Id = 13,
                            Force = 328,
                            Nom = "Ankokuji Ekei"
                        },
                        new
                        {
                            Id = 14,
                            Force = 1399,
                            Nom = "Aochi Shigetsuna"
                        },
                        new
                        {
                            Id = 15,
                            Force = 22,
                            Nom = "Aokage Takaakira"
                        },
                        new
                        {
                            Id = 16,
                            Force = 2,
                            Nom = "Aoki Kazushige"
                        },
                        new
                        {
                            Id = 17,
                            Force = 1296,
                            Nom = "Akahori Chohichi"
                        },
                        new
                        {
                            Id = 18,
                            Force = 1967,
                            Nom = "Arai Hakuseki"
                        },
                        new
                        {
                            Id = 19,
                            Force = 1968,
                            Nom = "Araki Motokiyo"
                        },
                        new
                        {
                            Id = 20,
                            Force = 612,
                            Nom = "Araki Murashige"
                        },
                        new
                        {
                            Id = 21,
                            Force = 668,
                            Nom = "Araki Muratsugu"
                        },
                        new
                        {
                            Id = 22,
                            Force = 1779,
                            Nom = "Arima Kihei"
                        },
                        new
                        {
                            Id = 23,
                            Force = 1387,
                            Nom = "Asakura Yoshikage"
                        },
                        new
                        {
                            Id = 24,
                            Force = 1531,
                            Nom = "Ayame Kagekatsu"
                        },
                        new
                        {
                            Id = 25,
                            Force = 514,
                            Nom = "Azai Hisamasa"
                        },
                        new
                        {
                            Id = 26,
                            Force = 461,
                            Nom = "Azai Nagamasa"
                        },
                        new
                        {
                            Id = 27,
                            Force = 321,
                            Nom = "Azai Sukemasa"
                        },
                        new
                        {
                            Id = 28,
                            Force = 1180,
                            Nom = "Baba Nobufusa"
                        },
                        new
                        {
                            Id = 29,
                            Force = 1422,
                            Nom = "Bessho Nagaharu"
                        },
                        new
                        {
                            Id = 30,
                            Force = 685,
                            Nom = "Chacha"
                        },
                        new
                        {
                            Id = 31,
                            Force = 1742,
                            Nom = "Chiba Shusaku Narimasa"
                        },
                        new
                        {
                            Id = 32,
                            Force = 1571,
                            Nom = "Chōsokabe Morichika"
                        },
                        new
                        {
                            Id = 33,
                            Force = 1171,
                            Nom = "Chōsokabe Kunichika"
                        },
                        new
                        {
                            Id = 34,
                            Force = 1600,
                            Nom = "Chōsokabe Motochika"
                        },
                        new
                        {
                            Id = 35,
                            Force = 1571,
                            Nom = "Chōsokabe Nobuchika"
                        },
                        new
                        {
                            Id = 36,
                            Force = 1840,
                            Nom = "Collache Eugène"
                        },
                        new
                        {
                            Id = 37,
                            Force = 1849,
                            Nom = "Date Masamune"
                        },
                        new
                        {
                            Id = 38,
                            Force = 1085,
                            Nom = "Date Shigezane"
                        },
                        new
                        {
                            Id = 39,
                            Force = 1283,
                            Nom = "Doi Toshikatsu"
                        },
                        new
                        {
                            Id = 40,
                            Force = 1834,
                            Nom = "Etō Shinpei"
                        },
                        new
                        {
                            Id = 41,
                            Force = 1973,
                            Nom = "Endō Naotsune"
                        },
                        new
                        {
                            Id = 42,
                            Force = 854,
                            Nom = "Enjoji Nobutane"
                        },
                        new
                        {
                            Id = 43,
                            Force = 1435,
                            Nom = "Enomoto Takeaki"
                        },
                        new
                        {
                            Id = 44,
                            Force = 941,
                            Nom = "Era Fusahide"
                        },
                        new
                        {
                            Id = 45,
                            Force = 1425,
                            Nom = "Fūma Kotarō"
                        },
                        new
                        {
                            Id = 46,
                            Force = 24,
                            Nom = "Fuwa Mitsuharu"
                        },
                        new
                        {
                            Id = 47,
                            Force = 1225,
                            Nom = "Fukushima Masanori"
                        },
                        new
                        {
                            Id = 48,
                            Force = 1004,
                            Nom = "Gamō Katahide"
                        },
                        new
                        {
                            Id = 49,
                            Force = 1198,
                            Nom = "Gamō Ujisato"
                        },
                        new
                        {
                            Id = 50,
                            Force = 1489,
                            Nom = "Harada Naomasa"
                        },
                        new
                        {
                            Id = 51,
                            Force = 162,
                            Nom = "Harada Nobutane"
                        },
                        new
                        {
                            Id = 52,
                            Force = 406,
                            Nom = "Harada Sanosuke"
                        },
                        new
                        {
                            Id = 53,
                            Force = 652,
                            Nom = "Hasekura Tsunenaga"
                        },
                        new
                        {
                            Id = 54,
                            Force = 1163,
                            Nom = "Hattori Hanzō"
                        },
                        new
                        {
                            Id = 55,
                            Force = 358,
                            Nom = "Hatano Hideharu"
                        },
                        new
                        {
                            Id = 56,
                            Force = 236,
                            Nom = "Hasegawa Eishin"
                        },
                        new
                        {
                            Id = 57,
                            Force = 415,
                            Nom = "Hayashizaki Jinsuke Shigenobu"
                        },
                        new
                        {
                            Id = 58,
                            Force = 1111,
                            Nom = "Hayashi Narinaga"
                        },
                        new
                        {
                            Id = 59,
                            Force = 848,
                            Nom = "Hijikata Toshizo"
                        },
                        new
                        {
                            Id = 60,
                            Force = 1383,
                            Nom = "Hirate Masahide"
                        },
                        new
                        {
                            Id = 61,
                            Force = 324,
                            Nom = "Hitotsubashi Keiki"
                        },
                        new
                        {
                            Id = 62,
                            Force = 876,
                            Nom = "Hōjō Masako"
                        },
                        new
                        {
                            Id = 63,
                            Force = 1577,
                            Nom = "Hōjō Tokimune"
                        },
                        new
                        {
                            Id = 64,
                            Force = 1158,
                            Nom = "Hōjō Ujiyasu"
                        },
                        new
                        {
                            Id = 65,
                            Force = 191,
                            Nom = "Hōjō Ujimasa"
                        },
                        new
                        {
                            Id = 66,
                            Force = 657,
                            Nom = "Honda Tadakatsu"
                        },
                        new
                        {
                            Id = 67,
                            Force = 909,
                            Nom = "Honda Tadatomo"
                        },
                        new
                        {
                            Id = 68,
                            Force = 1052,
                            Nom = "Honganji Kennyo"
                        },
                        new
                        {
                            Id = 69,
                            Force = 1143,
                            Nom = "Horio Yoshiharu"
                        },
                        new
                        {
                            Id = 70,
                            Force = 141,
                            Nom = "Hosokawa Fujitaka"
                        },
                        new
                        {
                            Id = 71,
                            Force = 1111,
                            Nom = "Hosokawa Gracia"
                        },
                        new
                        {
                            Id = 72,
                            Force = 710,
                            Nom = "Hosokawa Tadaoki"
                        },
                        new
                        {
                            Id = 73,
                            Force = 175,
                            Nom = "Hotta Masatoshi"
                        },
                        new
                        {
                            Id = 74,
                            Force = 1899,
                            Nom = "Ii Naoaki"
                        },
                        new
                        {
                            Id = 75,
                            Force = 1801,
                            Nom = "Ii Naomasa"
                        },
                        new
                        {
                            Id = 76,
                            Force = 1206,
                            Nom = "Ii Naomori"
                        },
                        new
                        {
                            Id = 77,
                            Force = 1563,
                            Nom = "Ii Naonaka"
                        },
                        new
                        {
                            Id = 78,
                            Force = 1167,
                            Nom = "Ii Naosuke"
                        },
                        new
                        {
                            Id = 79,
                            Force = 1722,
                            Nom = "Ii Naotaka"
                        },
                        new
                        {
                            Id = 80,
                            Force = 1513,
                            Nom = "Ii Naotora"
                        },
                        new
                        {
                            Id = 81,
                            Force = 1130,
                            Nom = "Ii Naoyuki"
                        },
                        new
                        {
                            Id = 82,
                            Force = 1439,
                            Nom = "Ii Naozumi"
                        },
                        new
                        {
                            Id = 83,
                            Force = 773,
                            Nom = "Iizasa Ienao"
                        },
                        new
                        {
                            Id = 84,
                            Force = 1550,
                            Nom = "Ijuin Tadaaki"
                        },
                        new
                        {
                            Id = 85,
                            Force = 282,
                            Nom = "Ikeda Tsuneoki"
                        },
                        new
                        {
                            Id = 86,
                            Force = 1936,
                            Nom = "Imagawa Ujizane"
                        },
                        new
                        {
                            Id = 87,
                            Force = 13,
                            Nom = "Imagawa Yoshimoto"
                        },
                        new
                        {
                            Id = 88,
                            Force = 1637,
                            Nom = "Imai Kanehira"
                        },
                        new
                        {
                            Id = 89,
                            Force = 1186,
                            Nom = "Inaba Yoshimichi"
                        },
                        new
                        {
                            Id = 90,
                            Force = 800,
                            Nom = "Inugami Nagayasu"
                        },
                        new
                        {
                            Id = 91,
                            Force = 6,
                            Nom = "Ishida Mitsunari"
                        },
                        new
                        {
                            Id = 92,
                            Force = 167,
                            Nom = "Isshiki Fujinaga"
                        },
                        new
                        {
                            Id = 93,
                            Force = 187,
                            Nom = "Itagaki Nobukata"
                        },
                        new
                        {
                            Id = 94,
                            Force = 1500,
                            Nom = "Itō Hirobumi"
                        },
                        new
                        {
                            Id = 95,
                            Force = 399,
                            Nom = "Iwanari Tomomichi"
                        },
                        new
                        {
                            Id = 96,
                            Force = 1388,
                            Nom = "Jinbo Nagamoto"
                        },
                        new
                        {
                            Id = 97,
                            Force = 1271,
                            Nom = "Jonas Tönse"
                        },
                        new
                        {
                            Id = 98,
                            Force = 225,
                            Nom = "Kannan Kumar(Salem)"
                        },
                        new
                        {
                            Id = 99,
                            Force = 1082,
                            Nom = "Kakeda Toshimune"
                        },
                        new
                        {
                            Id = 100,
                            Force = 1826,
                            Nom = "Kaneko Ietada"
                        },
                        new
                        {
                            Id = 101,
                            Force = 422,
                            Nom = "Katagiri Katsumoto"
                        },
                        new
                        {
                            Id = 102,
                            Force = 1357,
                            Nom = "Katakura Kojūro"
                        },
                        new
                        {
                            Id = 103,
                            Force = 1236,
                            Nom = "Katakura Shigenaga"
                        },
                        new
                        {
                            Id = 104,
                            Force = 1304,
                            Nom = "Kataoka Mitsumasa"
                        },
                        new
                        {
                            Id = 105,
                            Force = 1846,
                            Nom = "Katō Kiyomasa"
                        },
                        new
                        {
                            Id = 106,
                            Force = 158,
                            Nom = "Kawakami Gensai"
                        },
                        new
                        {
                            Id = 107,
                            Force = 1751,
                            Nom = "Kido Takayoshi"
                        },
                        new
                        {
                            Id = 108,
                            Force = 1919,
                            Nom = "Kikkawa Hiroie"
                        },
                        new
                        {
                            Id = 109,
                            Force = 421,
                            Nom = "Kimotsuki Kanetsugu"
                        },
                        new
                        {
                            Id = 110,
                            Force = 451,
                            Nom = "Kitamura Kansuke"
                        },
                        new
                        {
                            Id = 111,
                            Force = 478,
                            Nom = "Kobayakawa Hideaki"
                        },
                        new
                        {
                            Id = 112,
                            Force = 1617,
                            Nom = "Kobayakawa Hidekane"
                        },
                        new
                        {
                            Id = 113,
                            Force = 855,
                            Nom = "Kobayakawa Takakage"
                        },
                        new
                        {
                            Id = 114,
                            Force = 105,
                            Nom = "Konishi Yukinaga"
                        },
                        new
                        {
                            Id = 115,
                            Force = 1857,
                            Nom = "Kojima Toyoharu"
                        },
                        new
                        {
                            Id = 116,
                            Force = 1652,
                            Nom = "Kuroda Kanbei"
                        },
                        new
                        {
                            Id = 117,
                            Force = 577,
                            Nom = "Kuroda Kiyotaka"
                        },
                        new
                        {
                            Id = 118,
                            Force = 869,
                            Nom = "Kusunoki Masashige"
                        },
                        new
                        {
                            Id = 119,
                            Force = 714,
                            Nom = "Kuwana Tarozaemon"
                        },
                        new
                        {
                            Id = 120,
                            Force = 1197,
                            Nom = "Kumagai Naozane"
                        },
                        new
                        {
                            Id = 121,
                            Force = 34,
                            Nom = "Maeda Keiji"
                        },
                        new
                        {
                            Id = 122,
                            Force = 1653,
                            Nom = "Maeda Matsu"
                        },
                        new
                        {
                            Id = 123,
                            Force = 1442,
                            Nom = "Maeda Nagatane"
                        },
                        new
                        {
                            Id = 124,
                            Force = 1098,
                            Nom = "Maeda Toshiie"
                        },
                        new
                        {
                            Id = 125,
                            Force = 426,
                            Nom = "Maeda Toshinaga"
                        },
                        new
                        {
                            Id = 126,
                            Force = 270,
                            Nom = "Maeda Toshitsune"
                        },
                        new
                        {
                            Id = 127,
                            Force = 689,
                            Nom = "Magome Kageyu"
                        },
                        new
                        {
                            Id = 128,
                            Force = 1882,
                            Nom = "Manabe Akifusa"
                        },
                        new
                        {
                            Id = 129,
                            Force = 310,
                            Nom = "Matsudaira Katamori"
                        },
                        new
                        {
                            Id = 130,
                            Force = 699,
                            Nom = "Matsudaira Nobutsuna"
                        },
                        new
                        {
                            Id = 131,
                            Force = 1260,
                            Nom = "Matsudaira Nobuyasu"
                        },
                        new
                        {
                            Id = 132,
                            Force = 1242,
                            Nom = "Matsudaira Higo no Kami Katamori"
                        },
                        new
                        {
                            Id = 133,
                            Force = 1943,
                            Nom = "Matsudaira Sadanobu"
                        },
                        new
                        {
                            Id = 134,
                            Force = 1121,
                            Nom = "Matsudaira Tadayoshi"
                        },
                        new
                        {
                            Id = 135,
                            Force = 954,
                            Nom = "Matsudaira Teru"
                        },
                        new
                        {
                            Id = 136,
                            Force = 1351,
                            Nom = "Matsunaga Hisahide"
                        },
                        new
                        {
                            Id = 137,
                            Force = 645,
                            Nom = "Matsunaga Hisamichi"
                        },
                        new
                        {
                            Id = 138,
                            Force = 1896,
                            Nom = "Matsuo Bashō"
                        },
                        new
                        {
                            Id = 139,
                            Force = 1303,
                            Nom = "Matsudaira Motoyasu"
                        },
                        new
                        {
                            Id = 140,
                            Force = 105,
                            Nom = "Minamoto no Mitsunaka"
                        },
                        new
                        {
                            Id = 141,
                            Force = 1013,
                            Nom = "Minamoto no Yoshiie"
                        },
                        new
                        {
                            Id = 142,
                            Force = 1227,
                            Nom = "Minamoto no Yoshimitsu"
                        },
                        new
                        {
                            Id = 143,
                            Force = 598,
                            Nom = "Minamoto no Yoshinaka"
                        },
                        new
                        {
                            Id = 144,
                            Force = 308,
                            Nom = "Minamoto no Yoshitomo"
                        },
                        new
                        {
                            Id = 145,
                            Force = 201,
                            Nom = "Minamoto no Yoshitsune"
                        },
                        new
                        {
                            Id = 146,
                            Force = 736,
                            Nom = "Minamoto no Tameyoshi"
                        },
                        new
                        {
                            Id = 147,
                            Force = 1520,
                            Nom = "Minamoto no Yorimasa"
                        },
                        new
                        {
                            Id = 148,
                            Force = 1882,
                            Nom = "Minamoto no Yorimitsu"
                        },
                        new
                        {
                            Id = 149,
                            Force = 308,
                            Nom = "Minamoto no Yoritomo"
                        },
                        new
                        {
                            Id = 150,
                            Force = 795,
                            Nom = "Minamoto no Noriyori"
                        },
                        new
                        {
                            Id = 151,
                            Force = 1696,
                            Nom = "Minoro Takashi"
                        },
                        new
                        {
                            Id = 152,
                            Force = 795,
                            Nom = "Miura Anjin"
                        },
                        new
                        {
                            Id = 153,
                            Force = 71,
                            Nom = "Miura Yoshimoto"
                        },
                        new
                        {
                            Id = 154,
                            Force = 559,
                            Nom = "Miyamoto Musashi"
                        },
                        new
                        {
                            Id = 155,
                            Force = 1464,
                            Nom = "Miyoshi Chōkei"
                        },
                        new
                        {
                            Id = 156,
                            Force = 805,
                            Nom = "Miyoshi Kazuhide"
                        },
                        new
                        {
                            Id = 157,
                            Force = 143,
                            Nom = "Miyoshi Masaga"
                        },
                        new
                        {
                            Id = 158,
                            Force = 1924,
                            Nom = "Miyoshi Masayasu"
                        },
                        new
                        {
                            Id = 159,
                            Force = 796,
                            Nom = "Miyoshi Moriyata"
                        },
                        new
                        {
                            Id = 160,
                            Force = 495,
                            Nom = "Miyoshi Nagayuki"
                        },
                        new
                        {
                            Id = 161,
                            Force = 1263,
                            Nom = "Miyoshi Yoshitsugu"
                        },
                        new
                        {
                            Id = 162,
                            Force = 1931,
                            Nom = "Mizuno Tadakuni"
                        },
                        new
                        {
                            Id = 163,
                            Force = 990,
                            Nom = "Moniwa Yoshinao"
                        },
                        new
                        {
                            Id = 164,
                            Force = 1042,
                            Nom = "Mōri Motonari"
                        },
                        new
                        {
                            Id = 165,
                            Force = 436,
                            Nom = "Mōri Nagasada"
                        },
                        new
                        {
                            Id = 166,
                            Force = 109,
                            Nom = "Mori Nagayoshi"
                        },
                        new
                        {
                            Id = 167,
                            Force = 119,
                            Nom = "Mōri Okimoto"
                        },
                        new
                        {
                            Id = 168,
                            Force = 1867,
                            Nom = "Mori Ranmaru"
                        },
                        new
                        {
                            Id = 169,
                            Force = 247,
                            Nom = "Mōri Takamoto"
                        },
                        new
                        {
                            Id = 170,
                            Force = 1429,
                            Nom = "Mori Tadamasa"
                        },
                        new
                        {
                            Id = 171,
                            Force = 1160,
                            Nom = "Mōri Terumoto"
                        },
                        new
                        {
                            Id = 172,
                            Force = 260,
                            Nom = "Mori Yoshinari"
                        },
                        new
                        {
                            Id = 173,
                            Force = 1591,
                            Nom = "Murai Sadakatsu"
                        },
                        new
                        {
                            Id = 174,
                            Force = 1054,
                            Nom = "Nagakura Shinpachi"
                        },
                        new
                        {
                            Id = 175,
                            Force = 1625,
                            Nom = "Nagao Harukage"
                        },
                        new
                        {
                            Id = 176,
                            Force = 586,
                            Nom = "Nagao Kagenobu"
                        },
                        new
                        {
                            Id = 177,
                            Force = 1540,
                            Nom = "Nagao Masakage"
                        },
                        new
                        {
                            Id = 178,
                            Force = 1055,
                            Nom = "Nagao Tamekage"
                        },
                        new
                        {
                            Id = 179,
                            Force = 1535,
                            Nom = "Nakagawa Kiyohide"
                        },
                        new
                        {
                            Id = 180,
                            Force = 382,
                            Nom = "Nakaoka Shintarō"
                        },
                        new
                        {
                            Id = 181,
                            Force = 433,
                            Nom = "Naoe Kagetsuna"
                        },
                        new
                        {
                            Id = 182,
                            Force = 1296,
                            Nom = "Naoe Kanetsugu"
                        },
                        new
                        {
                            Id = 183,
                            Force = 1292,
                            Nom = "Narita Kaihime"
                        },
                        new
                        {
                            Id = 184,
                            Force = 77,
                            Nom = "Nene"
                        },
                        new
                        {
                            Id = 185,
                            Force = 765,
                            Nom = "Nihonmatsu Yoshitsugu"
                        },
                        new
                        {
                            Id = 186,
                            Force = 1558,
                            Nom = "Niimi Nishiki"
                        },
                        new
                        {
                            Id = 187,
                            Force = 417,
                            Nom = "Niiro Tadamoto"
                        },
                        new
                        {
                            Id = 188,
                            Force = 1541,
                            Nom = "Niwa Nagahide"
                        },
                        new
                        {
                            Id = 189,
                            Force = 1156,
                            Nom = "Niwa Nagashige"
                        },
                        new
                        {
                            Id = 190,
                            Force = 1745,
                            Nom = "Oda Hiroyoshi"
                        },
                        new
                        {
                            Id = 191,
                            Force = 1225,
                            Nom = "Oda Nobuhide"
                        },
                        new
                        {
                            Id = 192,
                            Force = 37,
                            Nom = "Oda Nobukata"
                        },
                        new
                        {
                            Id = 193,
                            Force = 873,
                            Nom = "Oda Nobukiyo"
                        },
                        new
                        {
                            Id = 194,
                            Force = 1353,
                            Nom = "Oda Nobunaga"
                        },
                        new
                        {
                            Id = 195,
                            Force = 1680,
                            Nom = "Oda Nobutada"
                        },
                        new
                        {
                            Id = 196,
                            Force = 747,
                            Nom = "Oda Nobutomo"
                        },
                        new
                        {
                            Id = 197,
                            Force = 1479,
                            Nom = "Oda Nobukatsu"
                        },
                        new
                        {
                            Id = 198,
                            Force = 1520,
                            Nom = "Oda Nobuyasu"
                        },
                        new
                        {
                            Id = 199,
                            Force = 675,
                            Nom = "Ogasawara Shōsai"
                        },
                        new
                        {
                            Id = 200,
                            Force = 1889,
                            Nom = "Ōishi Kuranosuke"
                        },
                        new
                        {
                            Id = 201,
                            Force = 101,
                            Nom = "Okada Izō"
                        },
                        new
                        {
                            Id = 202,
                            Force = 1735,
                            Nom = "Judge Ooka"
                        },
                        new
                        {
                            Id = 203,
                            Force = 1659,
                            Nom = "Ōta Dōkan"
                        },
                        new
                        {
                            Id = 204,
                            Force = 556,
                            Nom = "Ōtani Yoshitsugu"
                        },
                        new
                        {
                            Id = 205,
                            Force = 107,
                            Nom = "Ōtani Yoshiharu"
                        },
                        new
                        {
                            Id = 206,
                            Force = 830,
                            Nom = "Ōtomo Sōrin"
                        },
                        new
                        {
                            Id = 207,
                            Force = 773,
                            Nom = "Okita Sōji"
                        },
                        new
                        {
                            Id = 208,
                            Force = 913,
                            Nom = "Ōkubo Toshimichi"
                        },
                        new
                        {
                            Id = 209,
                            Force = 641,
                            Nom = "Okunomiya Masaie"
                        },
                        new
                        {
                            Id = 210,
                            Force = 167,
                            Nom = "Ōuchi Yoshitaka"
                        },
                        new
                        {
                            Id = 211,
                            Force = 212,
                            Nom = "Omy Yoshika"
                        },
                        new
                        {
                            Id = 212,
                            Force = 1902,
                            Nom = "Pore Sufi"
                        },
                        new
                        {
                            Id = 213,
                            Force = 621,
                            Nom = "Reizei Takatoyo"
                        },
                        new
                        {
                            Id = 214,
                            Force = 1883,
                            Nom = "Rokkaku Sadayori"
                        },
                        new
                        {
                            Id = 215,
                            Force = 149,
                            Nom = "Rokkaku Yoshiharu"
                        },
                        new
                        {
                            Id = 216,
                            Force = 589,
                            Nom = "Rokkaku Yoshikata"
                        },
                        new
                        {
                            Id = 217,
                            Force = 313,
                            Nom = "Rusu Masakage"
                        },
                        new
                        {
                            Id = 218,
                            Force = 14,
                            Nom = "Ryūzōji Takanobu"
                        },
                        new
                        {
                            Id = 219,
                            Force = 944,
                            Nom = "Saigo Kiyokazu"
                        },
                        new
                        {
                            Id = 220,
                            Force = 1340,
                            Nom = "Saigō Masako"
                        },
                        new
                        {
                            Id = 221,
                            Force = 987,
                            Nom = "Sagara Taketō"
                        },
                        new
                        {
                            Id = 222,
                            Force = 1197,
                            Nom = "Saigō Takamori"
                        },
                        new
                        {
                            Id = 223,
                            Force = 902,
                            Nom = "Saigo Yoshikatsu"
                        },
                        new
                        {
                            Id = 224,
                            Force = 1673,
                            Nom = "Saitō Dōsan"
                        },
                        new
                        {
                            Id = 225,
                            Force = 741,
                            Nom = "Saitō Hajime"
                        },
                        new
                        {
                            Id = 226,
                            Force = 1603,
                            Nom = "Saito Musashibō Benkei"
                        },
                        new
                        {
                            Id = 227,
                            Force = 829,
                            Nom = "Saitō Yoshitatsu"
                        },
                        new
                        {
                            Id = 228,
                            Force = 931,
                            Nom = "Sakai Tadakiyo"
                        },
                        new
                        {
                            Id = 229,
                            Force = 558,
                            Nom = "Sakai Tadashige"
                        },
                        new
                        {
                            Id = 230,
                            Force = 1239,
                            Nom = "Sakai Tadatsugu"
                        },
                        new
                        {
                            Id = 231,
                            Force = 820,
                            Nom = "Sakai Tadayo"
                        },
                        new
                        {
                            Id = 232,
                            Force = 1396,
                            Nom = "Sakakibara Yasumasa"
                        },
                        new
                        {
                            Id = 233,
                            Force = 386,
                            Nom = "Sakamoto Ryōma"
                        },
                        new
                        {
                            Id = 234,
                            Force = 706,
                            Nom = "Sakuma Morimasa"
                        },
                        new
                        {
                            Id = 235,
                            Force = 801,
                            Nom = "Sakuma Nobumori"
                        },
                        new
                        {
                            Id = 236,
                            Force = 1460,
                            Nom = "Sanada Akihime"
                        },
                        new
                        {
                            Id = 237,
                            Force = 1335,
                            Nom = "Sanada Komatsuhime"
                        },
                        new
                        {
                            Id = 238,
                            Force = 847,
                            Nom = "Sanada Masayuki"
                        },
                        new
                        {
                            Id = 239,
                            Force = 1138,
                            Nom = "Sanada Nobuyuki"
                        },
                        new
                        {
                            Id = 240,
                            Force = 951,
                            Nom = "Sanada Yukimura"
                        },
                        new
                        {
                            Id = 241,
                            Force = 153,
                            Nom = "Sasaki Kojirō"
                        },
                        new
                        {
                            Id = 242,
                            Force = 1565,
                            Nom = "Sassa Narimasa"
                        },
                        new
                        {
                            Id = 243,
                            Force = 730,
                            Nom = "Sasuke Sarutobi"
                        },
                        new
                        {
                            Id = 244,
                            Force = 745,
                            Nom = "Serizawa Kamo"
                        },
                        new
                        {
                            Id = 245,
                            Force = 535,
                            Nom = "Shibata Katsuie"
                        },
                        new
                        {
                            Id = 246,
                            Force = 561,
                            Nom = "Shima Sakon"
                        },
                        new
                        {
                            Id = 247,
                            Force = 565,
                            Nom = "Shimada Ichirō"
                        },
                        new
                        {
                            Id = 248,
                            Force = 1018,
                            Nom = "Shimazu Katsuhisa"
                        },
                        new
                        {
                            Id = 249,
                            Force = 592,
                            Nom = "Shimazu Tadahisa"
                        },
                        new
                        {
                            Id = 250,
                            Force = 417,
                            Nom = "Shimazu Tadatsune"
                        },
                        new
                        {
                            Id = 251,
                            Force = 1453,
                            Nom = "Shimazu Tadayoshi"
                        },
                        new
                        {
                            Id = 252,
                            Force = 305,
                            Nom = "Shimazu Takahisa"
                        },
                        new
                        {
                            Id = 253,
                            Force = 1928,
                            Nom = "Shimazu Toyohisa"
                        },
                        new
                        {
                            Id = 254,
                            Force = 286,
                            Nom = "Shimazu Yoshihiro"
                        },
                        new
                        {
                            Id = 255,
                            Force = 783,
                            Nom = "Shimazu Yoshihisa"
                        },
                        new
                        {
                            Id = 256,
                            Force = 1653,
                            Nom = "Shindou Hiroshii"
                        },
                        new
                        {
                            Id = 257,
                            Force = 1612,
                            Nom = "Sogo Nagayasu"
                        },
                        new
                        {
                            Id = 258,
                            Force = 1167,
                            Nom = "Sue Yoshitaka"
                        },
                        new
                        {
                            Id = 259,
                            Force = 1568,
                            Nom = "Tachibana Muneshige"
                        },
                        new
                        {
                            Id = 260,
                            Force = 1490,
                            Nom = "Tachibana Dōsetsu"
                        },
                        new
                        {
                            Id = 261,
                            Force = 1214,
                            Nom = "Tachibana Ginchiyo"
                        },
                        new
                        {
                            Id = 262,
                            Force = 1914,
                            Nom = "Taigen Sessai"
                        },
                        new
                        {
                            Id = 263,
                            Force = 1791,
                            Nom = "Taira no Kiyomori"
                        },
                        new
                        {
                            Id = 264,
                            Force = 314,
                            Nom = "Taira Masakado"
                        },
                        new
                        {
                            Id = 265,
                            Force = 1108,
                            Nom = "Takahashi Shigetane"
                        },
                        new
                        {
                            Id = 266,
                            Force = 6,
                            Nom = "Takenaka Shigeharu"
                        },
                        new
                        {
                            Id = 267,
                            Force = 175,
                            Nom = "Takasugi Shinsaku"
                        },
                        new
                        {
                            Id = 268,
                            Force = 246,
                            Nom = "Takayama Justo"
                        },
                        new
                        {
                            Id = 269,
                            Force = 1055,
                            Nom = "Takayama Ukon"
                        },
                        new
                        {
                            Id = 270,
                            Force = 282,
                            Nom = "Takechi Hanpeita"
                        },
                        new
                        {
                            Id = 271,
                            Force = 271,
                            Nom = "Takeda Katsuyori"
                        },
                        new
                        {
                            Id = 272,
                            Force = 767,
                            Nom = "Takeda Nobukatsu"
                        },
                        new
                        {
                            Id = 273,
                            Force = 72,
                            Nom = "Takeda Nobushige"
                        },
                        new
                        {
                            Id = 274,
                            Force = 1586,
                            Nom = "Takeda Shingen"
                        },
                        new
                        {
                            Id = 275,
                            Force = 490,
                            Nom = "Takenaka Hanbei"
                        },
                        new
                        {
                            Id = 276,
                            Force = 1766,
                            Nom = "Tani Tadasumi"
                        },
                        new
                        {
                            Id = 277,
                            Force = 1872,
                            Nom = "Tōdō Takatora"
                        },
                        new
                        {
                            Id = 278,
                            Force = 618,
                            Nom = "Toki Yorinari"
                        },
                        new
                        {
                            Id = 279,
                            Force = 1424,
                            Nom = "Tochimitsu Gantyoki"
                        },
                        new
                        {
                            Id = 280,
                            Force = 1113,
                            Nom = "Tokugawa Ieyasu"
                        },
                        new
                        {
                            Id = 281,
                            Force = 122,
                            Nom = "Tokugawa Hidetada"
                        },
                        new
                        {
                            Id = 282,
                            Force = 1801,
                            Nom = "Tokugawa Nariaki"
                        },
                        new
                        {
                            Id = 283,
                            Force = 489,
                            Nom = "Tokugawa Yoshinobu"
                        },
                        new
                        {
                            Id = 284,
                            Force = 1018,
                            Nom = "Torii Mototada"
                        },
                        new
                        {
                            Id = 285,
                            Force = 1954,
                            Nom = "Toyotomi Hidenaga"
                        },
                        new
                        {
                            Id = 286,
                            Force = 39,
                            Nom = "Toyotomi Hideyoshi"
                        },
                        new
                        {
                            Id = 287,
                            Force = 1396,
                            Nom = "Toyotomi Hideyori"
                        },
                        new
                        {
                            Id = 288,
                            Force = 131,
                            Nom = "Tozuka Tadaharu"
                        },
                        new
                        {
                            Id = 289,
                            Force = 767,
                            Nom = "Tsukahara Bokuden"
                        },
                        new
                        {
                            Id = 290,
                            Force = 1317,
                            Nom = "Uesugi Kagekatsu"
                        },
                        new
                        {
                            Id = 291,
                            Force = 1285,
                            Nom = "Uesugi Kagetora"
                        },
                        new
                        {
                            Id = 292,
                            Force = 716,
                            Nom = "Uesugi Kenshin"
                        },
                        new
                        {
                            Id = 293,
                            Force = 464,
                            Nom = "Ujiie Naotomo"
                        },
                        new
                        {
                            Id = 294,
                            Force = 496,
                            Nom = "Ukita Naoie"
                        },
                        new
                        {
                            Id = 295,
                            Force = 532,
                            Nom = "Ukita Okiie"
                        },
                        new
                        {
                            Id = 296,
                            Force = 1694,
                            Nom = "Umezawa Michiharu"
                        },
                        new
                        {
                            Id = 297,
                            Force = 89,
                            Nom = "Usami Sadamitsu"
                        },
                        new
                        {
                            Id = 298,
                            Force = 374,
                            Nom = "Uyama Hisanobu"
                        },
                        new
                        {
                            Id = 299,
                            Force = 1866,
                            Nom = "Wada Shinsuke"
                        },
                        new
                        {
                            Id = 300,
                            Force = 1866,
                            Nom = "Watanabe Kazan"
                        },
                        new
                        {
                            Id = 301,
                            Force = 1867,
                            Nom = "Watanabe no Tsuna"
                        },
                        new
                        {
                            Id = 302,
                            Force = 1349,
                            Nom = "Yasumero Kenshin"
                        },
                        new
                        {
                            Id = 303,
                            Force = 955,
                            Nom = "Yagyū Jūbei Mitsuyoshi"
                        },
                        new
                        {
                            Id = 304,
                            Force = 128,
                            Nom = "Yagyū Munenori"
                        },
                        new
                        {
                            Id = 305,
                            Force = 444,
                            Nom = "Yamauchi Kazutoyo"
                        },
                        new
                        {
                            Id = 306,
                            Force = 683,
                            Nom = "Yamada Arinaga"
                        },
                        new
                        {
                            Id = 307,
                            Force = 1013,
                            Nom = "Yamada Arinobu"
                        },
                        new
                        {
                            Id = 308,
                            Force = 942,
                            Nom = "Yamada Nagamasa"
                        },
                        new
                        {
                            Id = 309,
                            Force = 1000,
                            Nom = "Yamagata Masakage"
                        },
                        new
                        {
                            Id = 310,
                            Force = 1914,
                            Nom = "Yamakawa Hiroshi"
                        },
                        new
                        {
                            Id = 311,
                            Force = 1582,
                            Nom = "Yamakawa Kenjirō"
                        },
                        new
                        {
                            Id = 312,
                            Force = 876,
                            Nom = "Yamakawa Naoe"
                        },
                        new
                        {
                            Id = 313,
                            Force = 1802,
                            Nom = "Yamanaka Yukimori"
                        },
                        new
                        {
                            Id = 314,
                            Force = 1316,
                            Nom = "Yamanami Keisuke"
                        },
                        new
                        {
                            Id = 315,
                            Force = 1675,
                            Nom = "Yamaoka Tesshū"
                        },
                        new
                        {
                            Id = 316,
                            Force = 350,
                            Nom = "Yanagawa Kenzaburo"
                        },
                        new
                        {
                            Id = 317,
                            Force = 1634,
                            Nom = "Yanagisawa Yoshiyasu"
                        },
                        new
                        {
                            Id = 318,
                            Force = 943,
                            Nom = "Yonekura Shigetsugu"
                        },
                        new
                        {
                            Id = 319,
                            Force = 702,
                            Nom = "Yūki Hideyasu"
                        },
                        new
                        {
                            Id = 320,
                            Force = 470,
                            Nom = "Yasuke"
                        });
                });

            modelBuilder.Entity("BO.Samourai", b =>
                {
                    b.HasOne("BO.Arme", "Arme")
                        .WithMany()
                        .HasForeignKey("ArmeId");

                    b.Navigation("Arme");
                });
#pragma warning restore 612, 618
        }
    }
}
