// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TPDojo.Data;

#nullable disable

namespace TPDojo.Migrations
{
    [DbContext(typeof(TPDojoContext))]
    partial class TPDojoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BO.Arme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Degats")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Armes");
                });

            modelBuilder.Entity("BO.Samourai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("ArmeId")
                        .HasColumnType("int");

                    b.Property<int>("Force")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArmeId");

                    b.ToTable("Samourais");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Force = 1702,
                            Nom = "Abe Masakatsu"
                        },
                        new
                        {
                            Id = 2,
                            Force = 551,
                            Nom = "Adachi Yasumori"
                        },
                        new
                        {
                            Id = 3,
                            Force = 1004,
                            Nom = "Adachi Kagemori"
                        },
                        new
                        {
                            Id = 4,
                            Force = 991,
                            Nom = "Adams William"
                        },
                        new
                        {
                            Id = 5,
                            Force = 704,
                            Nom = "Aiou Mototsuna"
                        },
                        new
                        {
                            Id = 6,
                            Force = 1420,
                            Nom = "Akai Terukage"
                        },
                        new
                        {
                            Id = 7,
                            Force = 1774,
                            Nom = "Akao Kiyotsuna"
                        },
                        new
                        {
                            Id = 8,
                            Force = 8,
                            Nom = "Akechi Mitsuhide"
                        },
                        new
                        {
                            Id = 9,
                            Force = 1797,
                            Nom = "Akiyama Nobutomo"
                        },
                        new
                        {
                            Id = 10,
                            Force = 1121,
                            Nom = "Amago Haruhisa"
                        },
                        new
                        {
                            Id = 11,
                            Force = 1794,
                            Nom = "Amago Yoshihisa"
                        },
                        new
                        {
                            Id = 12,
                            Force = 1046,
                            Nom = "Andō Morinari"
                        },
                        new
                        {
                            Id = 13,
                            Force = 1078,
                            Nom = "Ankokuji Ekei"
                        },
                        new
                        {
                            Id = 14,
                            Force = 374,
                            Nom = "Aochi Shigetsuna"
                        },
                        new
                        {
                            Id = 15,
                            Force = 271,
                            Nom = "Aokage Takaakira"
                        },
                        new
                        {
                            Id = 16,
                            Force = 216,
                            Nom = "Aoki Kazushige"
                        },
                        new
                        {
                            Id = 17,
                            Force = 1485,
                            Nom = "Akahori Chohichi"
                        },
                        new
                        {
                            Id = 18,
                            Force = 270,
                            Nom = "Arai Hakuseki"
                        },
                        new
                        {
                            Id = 19,
                            Force = 160,
                            Nom = "Araki Motokiyo"
                        },
                        new
                        {
                            Id = 20,
                            Force = 266,
                            Nom = "Araki Murashige"
                        },
                        new
                        {
                            Id = 21,
                            Force = 730,
                            Nom = "Araki Muratsugu"
                        },
                        new
                        {
                            Id = 22,
                            Force = 879,
                            Nom = "Arima Kihei"
                        },
                        new
                        {
                            Id = 23,
                            Force = 1912,
                            Nom = "Asakura Yoshikage"
                        },
                        new
                        {
                            Id = 24,
                            Force = 567,
                            Nom = "Ayame Kagekatsu"
                        },
                        new
                        {
                            Id = 25,
                            Force = 883,
                            Nom = "Azai Hisamasa"
                        },
                        new
                        {
                            Id = 26,
                            Force = 1927,
                            Nom = "Azai Nagamasa"
                        },
                        new
                        {
                            Id = 27,
                            Force = 1733,
                            Nom = "Azai Sukemasa"
                        },
                        new
                        {
                            Id = 28,
                            Force = 1116,
                            Nom = "Baba Nobufusa"
                        },
                        new
                        {
                            Id = 29,
                            Force = 1304,
                            Nom = "Bessho Nagaharu"
                        },
                        new
                        {
                            Id = 30,
                            Force = 124,
                            Nom = "Chacha"
                        },
                        new
                        {
                            Id = 31,
                            Force = 667,
                            Nom = "Chiba Shusaku Narimasa"
                        },
                        new
                        {
                            Id = 32,
                            Force = 1497,
                            Nom = "Chōsokabe Morichika"
                        },
                        new
                        {
                            Id = 33,
                            Force = 1854,
                            Nom = "Chōsokabe Kunichika"
                        },
                        new
                        {
                            Id = 34,
                            Force = 102,
                            Nom = "Chōsokabe Motochika"
                        },
                        new
                        {
                            Id = 35,
                            Force = 846,
                            Nom = "Chōsokabe Nobuchika"
                        },
                        new
                        {
                            Id = 36,
                            Force = 560,
                            Nom = "Collache Eugène"
                        },
                        new
                        {
                            Id = 37,
                            Force = 1214,
                            Nom = "Date Masamune"
                        },
                        new
                        {
                            Id = 38,
                            Force = 181,
                            Nom = "Date Shigezane"
                        },
                        new
                        {
                            Id = 39,
                            Force = 1032,
                            Nom = "Doi Toshikatsu"
                        },
                        new
                        {
                            Id = 40,
                            Force = 280,
                            Nom = "Etō Shinpei"
                        },
                        new
                        {
                            Id = 41,
                            Force = 233,
                            Nom = "Endō Naotsune"
                        },
                        new
                        {
                            Id = 42,
                            Force = 351,
                            Nom = "Enjoji Nobutane"
                        },
                        new
                        {
                            Id = 43,
                            Force = 380,
                            Nom = "Enomoto Takeaki"
                        },
                        new
                        {
                            Id = 44,
                            Force = 339,
                            Nom = "Era Fusahide"
                        },
                        new
                        {
                            Id = 45,
                            Force = 185,
                            Nom = "Fūma Kotarō"
                        },
                        new
                        {
                            Id = 46,
                            Force = 181,
                            Nom = "Fuwa Mitsuharu"
                        },
                        new
                        {
                            Id = 47,
                            Force = 437,
                            Nom = "Fukushima Masanori"
                        },
                        new
                        {
                            Id = 48,
                            Force = 649,
                            Nom = "Gamō Katahide"
                        },
                        new
                        {
                            Id = 49,
                            Force = 202,
                            Nom = "Gamō Ujisato"
                        },
                        new
                        {
                            Id = 50,
                            Force = 820,
                            Nom = "Harada Naomasa"
                        },
                        new
                        {
                            Id = 51,
                            Force = 928,
                            Nom = "Harada Nobutane"
                        },
                        new
                        {
                            Id = 52,
                            Force = 1220,
                            Nom = "Harada Sanosuke"
                        },
                        new
                        {
                            Id = 53,
                            Force = 97,
                            Nom = "Hasekura Tsunenaga"
                        },
                        new
                        {
                            Id = 54,
                            Force = 954,
                            Nom = "Hattori Hanzō"
                        },
                        new
                        {
                            Id = 55,
                            Force = 1016,
                            Nom = "Hatano Hideharu"
                        },
                        new
                        {
                            Id = 56,
                            Force = 1727,
                            Nom = "Hasegawa Eishin"
                        },
                        new
                        {
                            Id = 57,
                            Force = 780,
                            Nom = "Hayashizaki Jinsuke Shigenobu"
                        },
                        new
                        {
                            Id = 58,
                            Force = 1966,
                            Nom = "Hayashi Narinaga"
                        },
                        new
                        {
                            Id = 59,
                            Force = 1475,
                            Nom = "Hijikata Toshizo"
                        },
                        new
                        {
                            Id = 60,
                            Force = 149,
                            Nom = "Hirate Masahide"
                        },
                        new
                        {
                            Id = 61,
                            Force = 601,
                            Nom = "Hitotsubashi Keiki"
                        },
                        new
                        {
                            Id = 62,
                            Force = 1794,
                            Nom = "Hōjō Masako"
                        },
                        new
                        {
                            Id = 63,
                            Force = 677,
                            Nom = "Hōjō Tokimune"
                        },
                        new
                        {
                            Id = 64,
                            Force = 151,
                            Nom = "Hōjō Ujiyasu"
                        },
                        new
                        {
                            Id = 65,
                            Force = 493,
                            Nom = "Hōjō Ujimasa"
                        },
                        new
                        {
                            Id = 66,
                            Force = 873,
                            Nom = "Honda Tadakatsu"
                        },
                        new
                        {
                            Id = 67,
                            Force = 1552,
                            Nom = "Honda Tadatomo"
                        },
                        new
                        {
                            Id = 68,
                            Force = 831,
                            Nom = "Honganji Kennyo"
                        },
                        new
                        {
                            Id = 69,
                            Force = 960,
                            Nom = "Horio Yoshiharu"
                        },
                        new
                        {
                            Id = 70,
                            Force = 1720,
                            Nom = "Hosokawa Fujitaka"
                        },
                        new
                        {
                            Id = 71,
                            Force = 711,
                            Nom = "Hosokawa Gracia"
                        },
                        new
                        {
                            Id = 72,
                            Force = 1555,
                            Nom = "Hosokawa Tadaoki"
                        },
                        new
                        {
                            Id = 73,
                            Force = 869,
                            Nom = "Hotta Masatoshi"
                        },
                        new
                        {
                            Id = 74,
                            Force = 777,
                            Nom = "Ii Naoaki"
                        },
                        new
                        {
                            Id = 75,
                            Force = 291,
                            Nom = "Ii Naomasa"
                        },
                        new
                        {
                            Id = 76,
                            Force = 512,
                            Nom = "Ii Naomori"
                        },
                        new
                        {
                            Id = 77,
                            Force = 1947,
                            Nom = "Ii Naonaka"
                        },
                        new
                        {
                            Id = 78,
                            Force = 665,
                            Nom = "Ii Naosuke"
                        },
                        new
                        {
                            Id = 79,
                            Force = 807,
                            Nom = "Ii Naotaka"
                        },
                        new
                        {
                            Id = 80,
                            Force = 1475,
                            Nom = "Ii Naotora"
                        },
                        new
                        {
                            Id = 81,
                            Force = 934,
                            Nom = "Ii Naoyuki"
                        },
                        new
                        {
                            Id = 82,
                            Force = 832,
                            Nom = "Ii Naozumi"
                        },
                        new
                        {
                            Id = 83,
                            Force = 1921,
                            Nom = "Iizasa Ienao"
                        },
                        new
                        {
                            Id = 84,
                            Force = 1644,
                            Nom = "Ijuin Tadaaki"
                        },
                        new
                        {
                            Id = 85,
                            Force = 855,
                            Nom = "Ikeda Tsuneoki"
                        },
                        new
                        {
                            Id = 86,
                            Force = 1617,
                            Nom = "Imagawa Ujizane"
                        },
                        new
                        {
                            Id = 87,
                            Force = 1748,
                            Nom = "Imagawa Yoshimoto"
                        },
                        new
                        {
                            Id = 88,
                            Force = 254,
                            Nom = "Imai Kanehira"
                        },
                        new
                        {
                            Id = 89,
                            Force = 34,
                            Nom = "Inaba Yoshimichi"
                        },
                        new
                        {
                            Id = 90,
                            Force = 1326,
                            Nom = "Inugami Nagayasu"
                        },
                        new
                        {
                            Id = 91,
                            Force = 1916,
                            Nom = "Ishida Mitsunari"
                        },
                        new
                        {
                            Id = 92,
                            Force = 1045,
                            Nom = "Isshiki Fujinaga"
                        },
                        new
                        {
                            Id = 93,
                            Force = 553,
                            Nom = "Itagaki Nobukata"
                        },
                        new
                        {
                            Id = 94,
                            Force = 1746,
                            Nom = "Itō Hirobumi"
                        },
                        new
                        {
                            Id = 95,
                            Force = 157,
                            Nom = "Iwanari Tomomichi"
                        },
                        new
                        {
                            Id = 96,
                            Force = 547,
                            Nom = "Jinbo Nagamoto"
                        },
                        new
                        {
                            Id = 97,
                            Force = 81,
                            Nom = "Jonas Tönse"
                        },
                        new
                        {
                            Id = 98,
                            Force = 1414,
                            Nom = "Kannan Kumar(Salem)"
                        },
                        new
                        {
                            Id = 99,
                            Force = 872,
                            Nom = "Kakeda Toshimune"
                        },
                        new
                        {
                            Id = 100,
                            Force = 14,
                            Nom = "Kaneko Ietada"
                        },
                        new
                        {
                            Id = 101,
                            Force = 264,
                            Nom = "Katagiri Katsumoto"
                        },
                        new
                        {
                            Id = 102,
                            Force = 1986,
                            Nom = "Katakura Kojūro"
                        },
                        new
                        {
                            Id = 103,
                            Force = 611,
                            Nom = "Katakura Shigenaga"
                        },
                        new
                        {
                            Id = 104,
                            Force = 514,
                            Nom = "Kataoka Mitsumasa"
                        },
                        new
                        {
                            Id = 105,
                            Force = 281,
                            Nom = "Katō Kiyomasa"
                        },
                        new
                        {
                            Id = 106,
                            Force = 871,
                            Nom = "Kawakami Gensai"
                        },
                        new
                        {
                            Id = 107,
                            Force = 789,
                            Nom = "Kido Takayoshi"
                        },
                        new
                        {
                            Id = 108,
                            Force = 737,
                            Nom = "Kikkawa Hiroie"
                        },
                        new
                        {
                            Id = 109,
                            Force = 1219,
                            Nom = "Kimotsuki Kanetsugu"
                        },
                        new
                        {
                            Id = 110,
                            Force = 1967,
                            Nom = "Kitamura Kansuke"
                        },
                        new
                        {
                            Id = 111,
                            Force = 845,
                            Nom = "Kobayakawa Hideaki"
                        },
                        new
                        {
                            Id = 112,
                            Force = 1371,
                            Nom = "Kobayakawa Hidekane"
                        },
                        new
                        {
                            Id = 113,
                            Force = 1436,
                            Nom = "Kobayakawa Takakage"
                        },
                        new
                        {
                            Id = 114,
                            Force = 418,
                            Nom = "Konishi Yukinaga"
                        },
                        new
                        {
                            Id = 115,
                            Force = 1739,
                            Nom = "Kojima Toyoharu"
                        },
                        new
                        {
                            Id = 116,
                            Force = 360,
                            Nom = "Kuroda Kanbei"
                        },
                        new
                        {
                            Id = 117,
                            Force = 31,
                            Nom = "Kuroda Kiyotaka"
                        },
                        new
                        {
                            Id = 118,
                            Force = 905,
                            Nom = "Kusunoki Masashige"
                        },
                        new
                        {
                            Id = 119,
                            Force = 1144,
                            Nom = "Kuwana Tarozaemon"
                        },
                        new
                        {
                            Id = 120,
                            Force = 1183,
                            Nom = "Kumagai Naozane"
                        },
                        new
                        {
                            Id = 121,
                            Force = 457,
                            Nom = "Maeda Keiji"
                        },
                        new
                        {
                            Id = 122,
                            Force = 53,
                            Nom = "Maeda Matsu"
                        },
                        new
                        {
                            Id = 123,
                            Force = 1150,
                            Nom = "Maeda Nagatane"
                        },
                        new
                        {
                            Id = 124,
                            Force = 1165,
                            Nom = "Maeda Toshiie"
                        },
                        new
                        {
                            Id = 125,
                            Force = 258,
                            Nom = "Maeda Toshinaga"
                        },
                        new
                        {
                            Id = 126,
                            Force = 1141,
                            Nom = "Maeda Toshitsune"
                        },
                        new
                        {
                            Id = 127,
                            Force = 1543,
                            Nom = "Magome Kageyu"
                        },
                        new
                        {
                            Id = 128,
                            Force = 855,
                            Nom = "Manabe Akifusa"
                        },
                        new
                        {
                            Id = 129,
                            Force = 1745,
                            Nom = "Matsudaira Katamori"
                        },
                        new
                        {
                            Id = 130,
                            Force = 393,
                            Nom = "Matsudaira Nobutsuna"
                        },
                        new
                        {
                            Id = 131,
                            Force = 422,
                            Nom = "Matsudaira Nobuyasu"
                        },
                        new
                        {
                            Id = 132,
                            Force = 126,
                            Nom = "Matsudaira Higo no Kami Katamori"
                        },
                        new
                        {
                            Id = 133,
                            Force = 1875,
                            Nom = "Matsudaira Sadanobu"
                        },
                        new
                        {
                            Id = 134,
                            Force = 1069,
                            Nom = "Matsudaira Tadayoshi"
                        },
                        new
                        {
                            Id = 135,
                            Force = 781,
                            Nom = "Matsudaira Teru"
                        },
                        new
                        {
                            Id = 136,
                            Force = 260,
                            Nom = "Matsunaga Hisahide"
                        },
                        new
                        {
                            Id = 137,
                            Force = 470,
                            Nom = "Matsunaga Hisamichi"
                        },
                        new
                        {
                            Id = 138,
                            Force = 77,
                            Nom = "Matsuo Bashō"
                        },
                        new
                        {
                            Id = 139,
                            Force = 1147,
                            Nom = "Matsudaira Motoyasu"
                        },
                        new
                        {
                            Id = 140,
                            Force = 351,
                            Nom = "Minamoto no Mitsunaka"
                        },
                        new
                        {
                            Id = 141,
                            Force = 197,
                            Nom = "Minamoto no Yoshiie"
                        },
                        new
                        {
                            Id = 142,
                            Force = 1176,
                            Nom = "Minamoto no Yoshimitsu"
                        },
                        new
                        {
                            Id = 143,
                            Force = 1009,
                            Nom = "Minamoto no Yoshinaka"
                        },
                        new
                        {
                            Id = 144,
                            Force = 1880,
                            Nom = "Minamoto no Yoshitomo"
                        },
                        new
                        {
                            Id = 145,
                            Force = 1259,
                            Nom = "Minamoto no Yoshitsune"
                        },
                        new
                        {
                            Id = 146,
                            Force = 354,
                            Nom = "Minamoto no Tameyoshi"
                        },
                        new
                        {
                            Id = 147,
                            Force = 115,
                            Nom = "Minamoto no Yorimasa"
                        },
                        new
                        {
                            Id = 148,
                            Force = 1899,
                            Nom = "Minamoto no Yorimitsu"
                        },
                        new
                        {
                            Id = 149,
                            Force = 406,
                            Nom = "Minamoto no Yoritomo"
                        },
                        new
                        {
                            Id = 150,
                            Force = 1568,
                            Nom = "Minamoto no Noriyori"
                        },
                        new
                        {
                            Id = 151,
                            Force = 443,
                            Nom = "Minoro Takashi"
                        },
                        new
                        {
                            Id = 152,
                            Force = 1099,
                            Nom = "Miura Anjin"
                        },
                        new
                        {
                            Id = 153,
                            Force = 1849,
                            Nom = "Miura Yoshimoto"
                        },
                        new
                        {
                            Id = 154,
                            Force = 1628,
                            Nom = "Miyamoto Musashi"
                        },
                        new
                        {
                            Id = 155,
                            Force = 717,
                            Nom = "Miyoshi Chōkei"
                        },
                        new
                        {
                            Id = 156,
                            Force = 691,
                            Nom = "Miyoshi Kazuhide"
                        },
                        new
                        {
                            Id = 157,
                            Force = 1278,
                            Nom = "Miyoshi Masaga"
                        },
                        new
                        {
                            Id = 158,
                            Force = 1715,
                            Nom = "Miyoshi Masayasu"
                        },
                        new
                        {
                            Id = 159,
                            Force = 953,
                            Nom = "Miyoshi Moriyata"
                        },
                        new
                        {
                            Id = 160,
                            Force = 1668,
                            Nom = "Miyoshi Nagayuki"
                        },
                        new
                        {
                            Id = 161,
                            Force = 1666,
                            Nom = "Miyoshi Yoshitsugu"
                        },
                        new
                        {
                            Id = 162,
                            Force = 601,
                            Nom = "Mizuno Tadakuni"
                        },
                        new
                        {
                            Id = 163,
                            Force = 1430,
                            Nom = "Moniwa Yoshinao"
                        },
                        new
                        {
                            Id = 164,
                            Force = 282,
                            Nom = "Mōri Motonari"
                        },
                        new
                        {
                            Id = 165,
                            Force = 770,
                            Nom = "Mōri Nagasada"
                        },
                        new
                        {
                            Id = 166,
                            Force = 131,
                            Nom = "Mori Nagayoshi"
                        },
                        new
                        {
                            Id = 167,
                            Force = 1803,
                            Nom = "Mōri Okimoto"
                        },
                        new
                        {
                            Id = 168,
                            Force = 1241,
                            Nom = "Mori Ranmaru"
                        },
                        new
                        {
                            Id = 169,
                            Force = 1024,
                            Nom = "Mōri Takamoto"
                        },
                        new
                        {
                            Id = 170,
                            Force = 387,
                            Nom = "Mori Tadamasa"
                        },
                        new
                        {
                            Id = 171,
                            Force = 725,
                            Nom = "Mōri Terumoto"
                        },
                        new
                        {
                            Id = 172,
                            Force = 409,
                            Nom = "Mori Yoshinari"
                        },
                        new
                        {
                            Id = 173,
                            Force = 1403,
                            Nom = "Murai Sadakatsu"
                        },
                        new
                        {
                            Id = 174,
                            Force = 1607,
                            Nom = "Nagakura Shinpachi"
                        },
                        new
                        {
                            Id = 175,
                            Force = 1093,
                            Nom = "Nagao Harukage"
                        },
                        new
                        {
                            Id = 176,
                            Force = 1172,
                            Nom = "Nagao Kagenobu"
                        },
                        new
                        {
                            Id = 177,
                            Force = 368,
                            Nom = "Nagao Masakage"
                        },
                        new
                        {
                            Id = 178,
                            Force = 220,
                            Nom = "Nagao Tamekage"
                        },
                        new
                        {
                            Id = 179,
                            Force = 1893,
                            Nom = "Nakagawa Kiyohide"
                        },
                        new
                        {
                            Id = 180,
                            Force = 1015,
                            Nom = "Nakaoka Shintarō"
                        },
                        new
                        {
                            Id = 181,
                            Force = 670,
                            Nom = "Naoe Kagetsuna"
                        },
                        new
                        {
                            Id = 182,
                            Force = 1895,
                            Nom = "Naoe Kanetsugu"
                        },
                        new
                        {
                            Id = 183,
                            Force = 303,
                            Nom = "Narita Kaihime"
                        },
                        new
                        {
                            Id = 184,
                            Force = 1583,
                            Nom = "Nene"
                        },
                        new
                        {
                            Id = 185,
                            Force = 497,
                            Nom = "Nihonmatsu Yoshitsugu"
                        },
                        new
                        {
                            Id = 186,
                            Force = 649,
                            Nom = "Niimi Nishiki"
                        },
                        new
                        {
                            Id = 187,
                            Force = 928,
                            Nom = "Niiro Tadamoto"
                        },
                        new
                        {
                            Id = 188,
                            Force = 464,
                            Nom = "Niwa Nagahide"
                        },
                        new
                        {
                            Id = 189,
                            Force = 1899,
                            Nom = "Niwa Nagashige"
                        },
                        new
                        {
                            Id = 190,
                            Force = 1352,
                            Nom = "Oda Hiroyoshi"
                        },
                        new
                        {
                            Id = 191,
                            Force = 1268,
                            Nom = "Oda Nobuhide"
                        },
                        new
                        {
                            Id = 192,
                            Force = 1189,
                            Nom = "Oda Nobukata"
                        },
                        new
                        {
                            Id = 193,
                            Force = 1154,
                            Nom = "Oda Nobukiyo"
                        },
                        new
                        {
                            Id = 194,
                            Force = 50,
                            Nom = "Oda Nobunaga"
                        },
                        new
                        {
                            Id = 195,
                            Force = 720,
                            Nom = "Oda Nobutada"
                        },
                        new
                        {
                            Id = 196,
                            Force = 43,
                            Nom = "Oda Nobutomo"
                        },
                        new
                        {
                            Id = 197,
                            Force = 1521,
                            Nom = "Oda Nobukatsu"
                        },
                        new
                        {
                            Id = 198,
                            Force = 1395,
                            Nom = "Oda Nobuyasu"
                        },
                        new
                        {
                            Id = 199,
                            Force = 1645,
                            Nom = "Ogasawara Shōsai"
                        },
                        new
                        {
                            Id = 200,
                            Force = 1775,
                            Nom = "Ōishi Kuranosuke"
                        },
                        new
                        {
                            Id = 201,
                            Force = 110,
                            Nom = "Okada Izō"
                        },
                        new
                        {
                            Id = 202,
                            Force = 327,
                            Nom = "Judge Ooka"
                        },
                        new
                        {
                            Id = 203,
                            Force = 1771,
                            Nom = "Ōta Dōkan"
                        },
                        new
                        {
                            Id = 204,
                            Force = 1193,
                            Nom = "Ōtani Yoshitsugu"
                        },
                        new
                        {
                            Id = 205,
                            Force = 866,
                            Nom = "Ōtani Yoshiharu"
                        },
                        new
                        {
                            Id = 206,
                            Force = 1978,
                            Nom = "Ōtomo Sōrin"
                        },
                        new
                        {
                            Id = 207,
                            Force = 890,
                            Nom = "Okita Sōji"
                        },
                        new
                        {
                            Id = 208,
                            Force = 606,
                            Nom = "Ōkubo Toshimichi"
                        },
                        new
                        {
                            Id = 209,
                            Force = 1760,
                            Nom = "Okunomiya Masaie"
                        },
                        new
                        {
                            Id = 210,
                            Force = 442,
                            Nom = "Ōuchi Yoshitaka"
                        },
                        new
                        {
                            Id = 211,
                            Force = 1375,
                            Nom = "Omy Yoshika"
                        },
                        new
                        {
                            Id = 212,
                            Force = 1477,
                            Nom = "Pore Sufi"
                        },
                        new
                        {
                            Id = 213,
                            Force = 294,
                            Nom = "Reizei Takatoyo"
                        },
                        new
                        {
                            Id = 214,
                            Force = 1307,
                            Nom = "Rokkaku Sadayori"
                        },
                        new
                        {
                            Id = 215,
                            Force = 1649,
                            Nom = "Rokkaku Yoshiharu"
                        },
                        new
                        {
                            Id = 216,
                            Force = 851,
                            Nom = "Rokkaku Yoshikata"
                        },
                        new
                        {
                            Id = 217,
                            Force = 401,
                            Nom = "Rusu Masakage"
                        },
                        new
                        {
                            Id = 218,
                            Force = 83,
                            Nom = "Ryūzōji Takanobu"
                        },
                        new
                        {
                            Id = 219,
                            Force = 1221,
                            Nom = "Saigo Kiyokazu"
                        },
                        new
                        {
                            Id = 220,
                            Force = 232,
                            Nom = "Saigō Masako"
                        },
                        new
                        {
                            Id = 221,
                            Force = 1268,
                            Nom = "Sagara Taketō"
                        },
                        new
                        {
                            Id = 222,
                            Force = 50,
                            Nom = "Saigō Takamori"
                        },
                        new
                        {
                            Id = 223,
                            Force = 747,
                            Nom = "Saigo Yoshikatsu"
                        },
                        new
                        {
                            Id = 224,
                            Force = 574,
                            Nom = "Saitō Dōsan"
                        },
                        new
                        {
                            Id = 225,
                            Force = 237,
                            Nom = "Saitō Hajime"
                        },
                        new
                        {
                            Id = 226,
                            Force = 304,
                            Nom = "Saito Musashibō Benkei"
                        },
                        new
                        {
                            Id = 227,
                            Force = 351,
                            Nom = "Saitō Yoshitatsu"
                        },
                        new
                        {
                            Id = 228,
                            Force = 1046,
                            Nom = "Sakai Tadakiyo"
                        },
                        new
                        {
                            Id = 229,
                            Force = 933,
                            Nom = "Sakai Tadashige"
                        },
                        new
                        {
                            Id = 230,
                            Force = 810,
                            Nom = "Sakai Tadatsugu"
                        },
                        new
                        {
                            Id = 231,
                            Force = 810,
                            Nom = "Sakai Tadayo"
                        },
                        new
                        {
                            Id = 232,
                            Force = 666,
                            Nom = "Sakakibara Yasumasa"
                        },
                        new
                        {
                            Id = 233,
                            Force = 34,
                            Nom = "Sakamoto Ryōma"
                        },
                        new
                        {
                            Id = 234,
                            Force = 1737,
                            Nom = "Sakuma Morimasa"
                        },
                        new
                        {
                            Id = 235,
                            Force = 347,
                            Nom = "Sakuma Nobumori"
                        },
                        new
                        {
                            Id = 236,
                            Force = 559,
                            Nom = "Sanada Akihime"
                        },
                        new
                        {
                            Id = 237,
                            Force = 1935,
                            Nom = "Sanada Komatsuhime"
                        },
                        new
                        {
                            Id = 238,
                            Force = 1372,
                            Nom = "Sanada Masayuki"
                        },
                        new
                        {
                            Id = 239,
                            Force = 803,
                            Nom = "Sanada Nobuyuki"
                        },
                        new
                        {
                            Id = 240,
                            Force = 1748,
                            Nom = "Sanada Yukimura"
                        },
                        new
                        {
                            Id = 241,
                            Force = 1909,
                            Nom = "Sasaki Kojirō"
                        },
                        new
                        {
                            Id = 242,
                            Force = 1552,
                            Nom = "Sassa Narimasa"
                        },
                        new
                        {
                            Id = 243,
                            Force = 143,
                            Nom = "Sasuke Sarutobi"
                        },
                        new
                        {
                            Id = 244,
                            Force = 659,
                            Nom = "Serizawa Kamo"
                        },
                        new
                        {
                            Id = 245,
                            Force = 1972,
                            Nom = "Shibata Katsuie"
                        },
                        new
                        {
                            Id = 246,
                            Force = 1884,
                            Nom = "Shima Sakon"
                        },
                        new
                        {
                            Id = 247,
                            Force = 1986,
                            Nom = "Shimada Ichirō"
                        },
                        new
                        {
                            Id = 248,
                            Force = 1373,
                            Nom = "Shimazu Katsuhisa"
                        },
                        new
                        {
                            Id = 249,
                            Force = 1554,
                            Nom = "Shimazu Tadahisa"
                        },
                        new
                        {
                            Id = 250,
                            Force = 1611,
                            Nom = "Shimazu Tadatsune"
                        },
                        new
                        {
                            Id = 251,
                            Force = 1874,
                            Nom = "Shimazu Tadayoshi"
                        },
                        new
                        {
                            Id = 252,
                            Force = 1324,
                            Nom = "Shimazu Takahisa"
                        },
                        new
                        {
                            Id = 253,
                            Force = 990,
                            Nom = "Shimazu Toyohisa"
                        },
                        new
                        {
                            Id = 254,
                            Force = 1413,
                            Nom = "Shimazu Yoshihiro"
                        },
                        new
                        {
                            Id = 255,
                            Force = 1674,
                            Nom = "Shimazu Yoshihisa"
                        },
                        new
                        {
                            Id = 256,
                            Force = 1551,
                            Nom = "Shindou Hiroshii"
                        },
                        new
                        {
                            Id = 257,
                            Force = 1531,
                            Nom = "Sogo Nagayasu"
                        },
                        new
                        {
                            Id = 258,
                            Force = 1961,
                            Nom = "Sue Yoshitaka"
                        },
                        new
                        {
                            Id = 259,
                            Force = 1607,
                            Nom = "Tachibana Muneshige"
                        },
                        new
                        {
                            Id = 260,
                            Force = 737,
                            Nom = "Tachibana Dōsetsu"
                        },
                        new
                        {
                            Id = 261,
                            Force = 1775,
                            Nom = "Tachibana Ginchiyo"
                        },
                        new
                        {
                            Id = 262,
                            Force = 729,
                            Nom = "Taigen Sessai"
                        },
                        new
                        {
                            Id = 263,
                            Force = 712,
                            Nom = "Taira no Kiyomori"
                        },
                        new
                        {
                            Id = 264,
                            Force = 880,
                            Nom = "Taira Masakado"
                        },
                        new
                        {
                            Id = 265,
                            Force = 202,
                            Nom = "Takahashi Shigetane"
                        },
                        new
                        {
                            Id = 266,
                            Force = 1254,
                            Nom = "Takenaka Shigeharu"
                        },
                        new
                        {
                            Id = 267,
                            Force = 152,
                            Nom = "Takasugi Shinsaku"
                        },
                        new
                        {
                            Id = 268,
                            Force = 1848,
                            Nom = "Takayama Justo"
                        },
                        new
                        {
                            Id = 269,
                            Force = 1,
                            Nom = "Takayama Ukon"
                        },
                        new
                        {
                            Id = 270,
                            Force = 1539,
                            Nom = "Takechi Hanpeita"
                        },
                        new
                        {
                            Id = 271,
                            Force = 1228,
                            Nom = "Takeda Katsuyori"
                        },
                        new
                        {
                            Id = 272,
                            Force = 857,
                            Nom = "Takeda Nobukatsu"
                        },
                        new
                        {
                            Id = 273,
                            Force = 591,
                            Nom = "Takeda Nobushige"
                        },
                        new
                        {
                            Id = 274,
                            Force = 104,
                            Nom = "Takeda Shingen"
                        },
                        new
                        {
                            Id = 275,
                            Force = 959,
                            Nom = "Takenaka Hanbei"
                        },
                        new
                        {
                            Id = 276,
                            Force = 633,
                            Nom = "Tani Tadasumi"
                        },
                        new
                        {
                            Id = 277,
                            Force = 1279,
                            Nom = "Tōdō Takatora"
                        },
                        new
                        {
                            Id = 278,
                            Force = 1790,
                            Nom = "Toki Yorinari"
                        },
                        new
                        {
                            Id = 279,
                            Force = 1083,
                            Nom = "Tochimitsu Gantyoki"
                        },
                        new
                        {
                            Id = 280,
                            Force = 708,
                            Nom = "Tokugawa Ieyasu"
                        },
                        new
                        {
                            Id = 281,
                            Force = 1167,
                            Nom = "Tokugawa Hidetada"
                        },
                        new
                        {
                            Id = 282,
                            Force = 797,
                            Nom = "Tokugawa Nariaki"
                        },
                        new
                        {
                            Id = 283,
                            Force = 380,
                            Nom = "Tokugawa Yoshinobu"
                        },
                        new
                        {
                            Id = 284,
                            Force = 59,
                            Nom = "Torii Mototada"
                        },
                        new
                        {
                            Id = 285,
                            Force = 1598,
                            Nom = "Toyotomi Hidenaga"
                        },
                        new
                        {
                            Id = 286,
                            Force = 1628,
                            Nom = "Toyotomi Hideyoshi"
                        },
                        new
                        {
                            Id = 287,
                            Force = 524,
                            Nom = "Toyotomi Hideyori"
                        },
                        new
                        {
                            Id = 288,
                            Force = 13,
                            Nom = "Tozuka Tadaharu"
                        },
                        new
                        {
                            Id = 289,
                            Force = 856,
                            Nom = "Tsukahara Bokuden"
                        },
                        new
                        {
                            Id = 290,
                            Force = 954,
                            Nom = "Uesugi Kagekatsu"
                        },
                        new
                        {
                            Id = 291,
                            Force = 997,
                            Nom = "Uesugi Kagetora"
                        },
                        new
                        {
                            Id = 292,
                            Force = 817,
                            Nom = "Uesugi Kenshin"
                        },
                        new
                        {
                            Id = 293,
                            Force = 1367,
                            Nom = "Ujiie Naotomo"
                        },
                        new
                        {
                            Id = 294,
                            Force = 1315,
                            Nom = "Ukita Naoie"
                        },
                        new
                        {
                            Id = 295,
                            Force = 1529,
                            Nom = "Ukita Okiie"
                        },
                        new
                        {
                            Id = 296,
                            Force = 126,
                            Nom = "Umezawa Michiharu"
                        },
                        new
                        {
                            Id = 297,
                            Force = 587,
                            Nom = "Usami Sadamitsu"
                        },
                        new
                        {
                            Id = 298,
                            Force = 1447,
                            Nom = "Uyama Hisanobu"
                        },
                        new
                        {
                            Id = 299,
                            Force = 1166,
                            Nom = "Wada Shinsuke"
                        },
                        new
                        {
                            Id = 300,
                            Force = 458,
                            Nom = "Watanabe Kazan"
                        },
                        new
                        {
                            Id = 301,
                            Force = 381,
                            Nom = "Watanabe no Tsuna"
                        },
                        new
                        {
                            Id = 302,
                            Force = 1796,
                            Nom = "Yasumero Kenshin"
                        },
                        new
                        {
                            Id = 303,
                            Force = 563,
                            Nom = "Yagyū Jūbei Mitsuyoshi"
                        },
                        new
                        {
                            Id = 304,
                            Force = 1561,
                            Nom = "Yagyū Munenori"
                        },
                        new
                        {
                            Id = 305,
                            Force = 1792,
                            Nom = "Yamauchi Kazutoyo"
                        },
                        new
                        {
                            Id = 306,
                            Force = 429,
                            Nom = "Yamada Arinaga"
                        },
                        new
                        {
                            Id = 307,
                            Force = 935,
                            Nom = "Yamada Arinobu"
                        },
                        new
                        {
                            Id = 308,
                            Force = 493,
                            Nom = "Yamada Nagamasa"
                        },
                        new
                        {
                            Id = 309,
                            Force = 1408,
                            Nom = "Yamagata Masakage"
                        },
                        new
                        {
                            Id = 310,
                            Force = 67,
                            Nom = "Yamakawa Hiroshi"
                        },
                        new
                        {
                            Id = 311,
                            Force = 193,
                            Nom = "Yamakawa Kenjirō"
                        },
                        new
                        {
                            Id = 312,
                            Force = 108,
                            Nom = "Yamakawa Naoe"
                        },
                        new
                        {
                            Id = 313,
                            Force = 1241,
                            Nom = "Yamanaka Yukimori"
                        },
                        new
                        {
                            Id = 314,
                            Force = 1644,
                            Nom = "Yamanami Keisuke"
                        },
                        new
                        {
                            Id = 315,
                            Force = 1419,
                            Nom = "Yamaoka Tesshū"
                        },
                        new
                        {
                            Id = 316,
                            Force = 1230,
                            Nom = "Yanagawa Kenzaburo"
                        },
                        new
                        {
                            Id = 317,
                            Force = 751,
                            Nom = "Yanagisawa Yoshiyasu"
                        },
                        new
                        {
                            Id = 318,
                            Force = 621,
                            Nom = "Yonekura Shigetsugu"
                        },
                        new
                        {
                            Id = 319,
                            Force = 1580,
                            Nom = "Yūki Hideyasu"
                        },
                        new
                        {
                            Id = 320,
                            Force = 1052,
                            Nom = "Yasuke"
                        });
                });

            modelBuilder.Entity("BO.Samourai", b =>
                {
                    b.HasOne("BO.Arme", "Arme")
                        .WithMany()
                        .HasForeignKey("ArmeId");

                    b.Navigation("Arme");
                });
#pragma warning restore 612, 618
        }
    }
}
